name: npm
description: installs npm packages if cache is missed

inputs:
  installDependencies:
    description: 'whether to run npm install or not'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
        registry-url: 'https://npm.pkg.github.com'

    - name: Cache dependencies
      if: inputs.installDependencies == 'true'
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('yarn.lock') }}

    - name: Run npm install
      if: inputs.installDependencies == 'true' && steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install --frozen-lockfile
